# Copy this file and rename to 'secrets.yaml' in this same directory
#
# This is where you fill out secret stuff:

wifi_ssid: 'The name of your Wifi '
wifi_password: 'Your Wifi password'

mqtt_broker: 'IP Address of your MQTT broker in format: 192.168.7.156'
mqtt_username: 'username'
mqtt_password: 'password'
